---
name: Schedule

on:
  schedule:
    - cron: 15 11 * * *
  workflow_dispatch:

jobs:
  scan:
    strategy:
      matrix:
        image: [backend, frontend]

    name: Scan ${{ matrix.image }} image
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: write
      statuses: none
      # needed for `cosign attest`
      id-token: write
    steps:
      - run: echo "REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - uses: adfinis/container-scanning-action@v0.3.0
        with:
          image-ref: ghcr.io/${{ env.REPO }}/${{ matrix.image }}
          attest: true
          token: ${{ secrets.GITHUB_TOKEN }}
